package example

//AutoGenerated Go type schema for input
type AutoGenerated struct {
	Servers []struct {
		ID        string   `json:"id"`
		Protocols []string `json:"protocols"`
		Ports     []string `json:"ports"`
	} `json:"servers"`
	Networks []struct {
		ID     string `json:"id"`
		Public bool   `json:"public"`
	} `json:"networks"`
	Ports []struct {
		ID      string `json:"id"`
		Network string `json:"network"`
	} `json:"ports"`
}
